SELECT 
    SM.NAME,
    SUM(S.PRICE) 
FROM STOCKS S 
INNER JOIN RENT_LOGS RL ON S.ID = RL.ID
INNER JOIN STORE_MST SM ON S.STORE_MST_ID = SM.ID
GROUP BY SM.NAME;

SELECT
    SM.NAME AS レンタル店舗名
    ,C.NAME AS 顧客名
    ,S.NAME AS DVDタイトル
    ,TO_CHAR(RL.RENT_DATE,'YYYY MONTH dd DAY','Nls_date_language = AMERICAN') AS レンタル年月日
FROM
RENT_LOGS RL
INNER JOIN CUSTOMERS C
ON RL.CUSTOMER_ID = C.ID
INNER JOIN STOCKS S
ON RL.STOCK_ID = S.ID
INNER JOIN STORE_MST SM
ON S.STORE_MST_ID = SM.ID
ORDER BY
    SM.ID DESC
    ,DVDタイトル ASC
    ,RL.RENT_DATE DESC;